Overal styling. Added image on upload
joanpadolina/meesterproef-1920 pull request #31
Opened 2020-05-28 18:21 UTC by joanpadolina

I've added a homepage for some userflow. Can you please review it. thanks

2020-05-28 18:42 UTC, nlvo commented on views/partials/header.ejs
> +        </div>
Volgensmij heb je de div niet afgesloten

2020-05-28 18:45 UTC, nlvo commented on views/partials/head.ejs
> +    <link rel="stylesheet" href="./css/frontpage.css">
Je kunt de relative path meegeven volgensmij zonder de punt dus zoiets `<link rel="stylesheet" href="/css/frontpage.css">`

2020-05-28 18:46 UTC, joanpadolina commented on views/partials/header.ejs
> +        </div>
yes forgot

2020-05-28 18:46 UTC, joanpadolina commented on views/partials/head.ejs
> +    <link rel="stylesheet" href="./css/frontpage.css">
ohja haha

2020-05-28 18:49 UTC, nlvo requested changes
Er zijn een paar schoonheidsfoutjes die je nog even moet aanpassen, maar voor de rest goed bezig 😊

2020-05-28 18:59 UTC, joanpadolina reviewed
change minor mistakes

2020-05-28 19:04 UTC, nlvo approved these changes

2020-05-29 00:53 UTC, joanpadolina reviewed
@nlvo styles are updated

2020-05-29 07:19 UTC, merged